### PR TITLE
rename devider.html into divider.html #28

### PR DESCRIPTION
**Pull request by dilekuzulmez**
rename devider.html into divider.html #28

### CODE REVIEW

**Comment by atherdon** [comment]
Hi @dilekuzulmez and thank you for your help.
Did you also rename the file in the `typography` folder as well?

**Review by atherdon — CHANGES_REQUESTED** [review]
in order to make index-full script work - we should also rename the file that we connecting here

**Review by atherdon — APPROVED** [review]
Perfect. Huge thank you.

**Comment by atherdon** [comment]
@dilekuzulmez while I'm here - I want to give you something in return.
I have a few courses on Udemy, related to git and github.
I can generate free coupons and share them with you. 
What do you think about it? will it be useful to you

**Comment by dilekuzulmez** [comment]
> Perfect. Huge thank you.

My pleasure. :)

**Comment by dilekuzulmez** [comment]
> @dilekuzulmez while I'm here - I want to give you something in return.
> I have a few courses on Udemy, related to git and github.
> I can generate free coupons and share them with you.
> What do you think about it? will it be useful to you

Yes, it would be perfect! Thank you so much.

**Comment by atherdon** [comment]
here we go.
also, feel free to share with your friends. it's free for 3 days. just start all of them, and later you can go back and watch them when you have free time.

- https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=A7736E10FA1D0B23B6BF
- https://www.udemy.com/course/git-workflows-in-depth/?couponCode=A028C25E0B1FFF67D696
- https://www.udemy.com/course/start-to-use-github-pull-requests-like-a-master/?couponCode=F611E3EF44D38F9BFAFD
- https://www.udemy.com/course/anatomy-pull-requests-in-depth/?couponCode=D9B17F00EEF2EA2CBEC4
- https://www.udemy.com/course/advanced-scenarios-git-commands/?couponCode=E6E94A3E2B0A22CBC542

**Comment by dilekuzulmez** [comment]
> here we go.
> also, feel free to share with your friends. it's free for 3 days. just start all of them, and later you can go back and watch them when you have free time.
> 
> * https://www.udemy.com/course/git-basics-and-merging-process/?couponCode=A7736E10FA1D0B23B6BF
> * https://www.udemy.com/course/git-workflows-in-depth/?couponCode=A028C25E0B1FFF67D696
> * https://www.udemy.com/course/start-to-use-github-pull-requests-like-a-master/?couponCode=F611E3EF44D38F9BFAFD
> * https://www.udemy.com/course/anatomy-pull-requests-in-depth/?couponCode=D9B17F00EEF2EA2CBEC4
> * https://www.udemy.com/course/advanced-scenarios-git-commands/?couponCode=E6E94A3E2B0A22CBC542

Thank you very much!

**Comment by atherdon** [comment]
hi @dilekuzulmez, I just add a label as you requested.
Btw, if you want to learn more from us and help with some simple tasks - don't hesitate and tell us

**Comment by atherdon** [comment]
btw, my email is arthur.tkachenko.netweightit@gmail.com

**Comment by dilekuzulmez** [comment]
> hi @dilekuzulmez, I just add a label as you requested.
> Btw, if you want to learn more from us and help with some simple tasks - don't hesitate and tell us

thank you! :)

**Pull request merged**
