### PR TITLE
Update subtitle.js

### PR DESCRIPTION
**Pull request by mikhailnathanielabordo**
Update tag to `<h2>` since in .md `##` means `<h2>` tag and update the font size to `22px` so that it will not look like the `<h3>` tag when converted.

referenced the `<h2>` style on the snippets [here](https://github.com/atherdon/newsletters/tree/master/archive/Thematic/snippets#h2).

### CODE REVIEW

**Comment by atherdon** [comment]
just to let you know:
1) most content related parts was done while ago and tested on different cases. Best way to apply changes is simple - after all your fixes our tests should work as well. There a lot of small things that can go wrong.
2) `master` branch contains latest state of the code. But generator might be broken. Because of different reasons.
The working version of generator located in `plain-working-version` branch. 


after all these things - should I merge your pull request?

**Comment by mikhailnathanielabordo** [comment]
yeah. I see no difference for the change here. I just change the format for the MD. since it's using `<p>` instead of the proper `<h2>` so I think this is fine. I'm also using this format on my local which seems to have no problem at all when generating html. :)

**Comment by atherdon** [comment]
well. i had so much pain with these newsletters, so I'm very pessimistic about everything. will check it tomorrow if you don't mind

**Review by atherdon — COMMENTED** [review]
i'll reject this pull request, sorry.
it's hard to catch mistakes, but I think you removed some styles that are crucial for render in stupid inboxes

**Comment by atherdon** [comment]
feel free to make fewer changes and submit it again

**Pull request closed without merging**
